username = input('Введите имя пользователя:' )
title = input('Введите заголовок заметки:' )
content = input('Опишите заметку:' )
status = input('Укажите статус заметки:' )
created_date = input('Введите дату создания заметки в формате (дд.мм.):')
issue_date = input('Введите дату истечения заметки (дедлайн) в формате (дд.мм.):')

print(username)
print(title)
print(content)
print(status)
print(created_date[0:5])
print(issue_date[0:5])
